backend:
  name: github
  repo: bhuvi28/mm-earthmovers
  branch: mm-preview
  base_url: https://mm-earthmovers-git-mm-preview-bhuvan-mehta-2s-projects.vercel.app/ # CHANGE THIS TO YOUR VERCEL DOMAIN
  auth_endpoint: api/auth

local_backend: true


media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Part Name", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Motor Grader", "Loader", "Excavator", "Other"]}
      - {label: "Brand/Model (Loader)", name: "brand_loader", widget: "select", required: false, condition: {field: "category", value: "Loader"}, options: [
          {label: "HM 2021D", value: "hm-2021d"},
          {label: "L&T 9020", value: "lt-9020"},
          {label: "LiuGong", value: "liugong"},
          {label: "SDLG", value: "sdlg"},
          {label: "SEM", value: "sem"},
          {label: "JCB", value: "jcb"}
        ]}
      - {label: "Brand/Model (Grader)", name: "brand_grader", widget: "select", required: false, condition: {field: "category", value: "Motor Grader"}, options: [
          {label: "CAT", value: "cat"},
          {label: "BEML", value: "beml"}
        ]}
      - {label: "Brand/Model (Excavator)", name: "brand_excavator", widget: "select", required: false, condition: {field: "category", value: "Excavator"}, options: [
          {label: "Hyundai", value: "hyundai"},
          {label: "Tata Hitachi", value: "tata-hitachi"},
          {label: "Volvo", value: "volvo"},
          {label: "Kobelco", value: "kobelco"},
          {label: "L&T Komatsu", value: "lt-komatsu"}
        ]}
      - {label: "Sizes Available", name: "sizes", widget: "string", required: false, hint: "Enter sizes separated by commas (e.g. 10mm, 20mm)"}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
