backend:
  name: github
  repo: bhuvi28/mm-earthmovers
  branch: main
  base_url: https://www.mmearthmovers.com
  auth_endpoint: api/auth

local_backend: false
publish_mode: editorial_workflow


media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Part Name", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Motor Grader", "Loader", "Excavator", "Other"]}
      - {label: "Company Name", name: "brand", widget: "select", required: false, options: [
          "HM 2021", "HM 2021 B", "HM 2021 D", "HM 2021 E", "TATA 3036", "L&T 9020",
          "JCB 430", "BEML BG 605/511", "BEML BG 605","BEML BG 511",
          "SLDG", "XCMG", "LIUGONG", "JCB 3DX"
        ]}
      - {label: "Part Number", name: "part_number", widget: "string", required: false, hint: "Enter part number. For multiple part numbers, separate with ' / ' (e.g., '12345 / 67890')"}
      - {label: "Display Priority", name: "priority", widget: "number", required: false, default: 999, hint: "Lower numbers appear first (e.g., 1, 2, 3). Leave blank or use 999 for alphabetical order."}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
