backend:
  name: github
  repo: bhuvi28/mm-earthmovers
  branch: mm-preview
  base_url: https://mm-earthmovers-git-mm-preview-bhuvan-mehta-2s-projects.vercel.app/ # CHANGE THIS TO YOUR VERCEL DOMAIN
  auth_endpoint: api/auth

local_backend: true
publish_mode: editorial_workflow


media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Part Name", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Motor Grader", "Loader", "Excavator", "Other"]}
      - {label: "Company Name", name: "brand", widget: "select", required: false, options: [
          "HM 2021D", "L&T 9020", "LiuGong", "SDLG", "SEM", "JCB",
          "CAT", "BEML",
          "Hyundai", "Tata Hitachi", "Volvo", "Kobelco", "L&T Komatsu"
        ]}
      - {label: "Part Number", name: "part_number", widget: "string", required: false, hint: "Enter part number"}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
